### ISSUE TITLE
bigger classes field to improve ux

### ISSUE THREAD

**Issue by bremercreative** [orgrosua/yabe-bricksbender#4]
is it possible to make the classes field bigger by default? i have issues working with classes, especially when the first row is full, it's not always automatically extending to new rows from there which results in clicking into other classes by mistake and sometimes changing things you don't want to change. 
to have a 3-4 lines field by default would solve this (for me)

![434135023_10231889558803109_1685641099808889884_n](https://github.com/orgrosua/yabe-bricksbender/assets/146111152/c258339d-02e7-4ed7-87c7-6cf0f832e5e6)

**Comment by blacksparrow78** [comment]
If I cant have a collapsable pop-out window for this, then I agree with this suggestion
