### ISSUE TITLE
Color Code Class Badges in Bricks Builder

### ISSUE THREAD

**Issue by blacksparrow78** [orgrosua/yabe-bricksbender#6]
For the color tags. I was just thinking ability to have some color differentiation between all the class badges so they arent all gray. For instance classes for padding and margin could be blue, classes for text, font, etc could be green, classes for layout orange, etc...I think it would be helpful for quick visual recognition if we needed to find a class to change, or remove. Especially when we have an element with several classes applied...

**Comment by wilcastell** [comment]
I like the idea, although it would seem more functional if the colors were grouped by breakpoint size, so it would be easier to see which classes are used on each screen size at a glance
